version: 2.0

jobs:
  bundle_dependencies:
    working_directory: ~/pragma-rails-starter
    docker:
      - image: ruby:2.4.2
    steps:
      - checkout
      - attach_workspace:
          at: ~/pragma-rails-starter
      - type: cache-restore
        key: pragma-rails-starter-{{ checksum "Gemfile.lock" }}
      - run: bundle check --path vendor/bundle || bundle install --path vendor/bundle
      - type: cache-save
        key: pragma-rails-starter-{{ checksum "Gemfile.lock" }}
        paths:
          - ~/pragma-rails-starter/vendor/bundle
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle

  test:
    working_directory: ~/pragma-rails-starter
    docker:
      - image: ruby:2.4.2
        environment:
          - PG_HOST=localhost
          - PG_USER=ubuntu
          - RAILS_ENV=test
          - RACK_ENV=test
          - DATABASE_URL=postgres://ubuntu@localhost:5432/pragma-rails-starter
      - image: postgres
        environment:
          - POSTGRES_USER=ubuntu
          - POSTGRES_DB=pragma-rails-starter
      - image: redis
    steps:
      - checkout
      - attach_workspace:
          at: ~/pragma-rails-starter
      - run: bundle --path vendor/bundle
      - run: cp config/application.example.yml config/application.yml
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            --no-color \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - type: store_test_results
        path: /tmp/test-results

  heroku_deploy:
    working_directory: ~/pragma-rails-starter
    docker:
      - image: ruby:2.4.2
    steps:
      - checkout
      - attach_workspace:
          at: ~/pragma-rails-starter
      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "my:ssh:key:fingerprint"
      - deploy:
          name: Deploy to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push heroku-production master
            fi

            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              git push heroku-staging staging:master
            fi

            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              git push heroku-dev develop:master
            fi

  eb_deploy:
    working_directory: ~/pragma-rails-starter
    docker:
      - image: ruby:2.4.2
    steps:
      - checkout
      - attach_workspace:
          at: ~/pragma-rails-starter
      - deploy:
          name: Deploy to EB
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              bash .circleci/setup-eb.sh
              apt-get update -qq
              apt-get upgrade -y -qq
              apt-get install -y python-dev python-pip
              easy_install --upgrade six
              pip install awsebcli
              eb deploy develop
            fi

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - bundle_dependencies
      - test:
          requires:
            - bundle_dependencies
      - heroku_deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - staging
                - master
      - eb_deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - staging
                - master
